### ISSUE TITLE
Fix Edge App yml setting headlines to make it more human readable. 

### ISSUE THREAD

**Issue by salmanfarisvp** [Screenly/Playground#189]
Fix https://github.com/Screenly/Playground/blob/master/edge-apps/countdown-timer/screenly.yml 

For example 
```
 Countdown_headline:
    type: string
    default_value: New Year Countdown
    title: countdown_headline
    optional: false
    help_text: Countdown header text value.
```

Fix the 

`title: countdown_headline` 

Humans readable format. 

Correct one 

`title: Countdown Timer Headline`
